services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d

